# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configPreview.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 109)
        Form.setStyleSheet("background-color: rgb(255, 189, 196);\n"
"background-color: rgba(248, 220, 255, 50);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.length = QtWidgets.QLabel(Form)
        self.length.setObjectName("length")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.length)
        self.lengthChangable = QtWidgets.QLineEdit(Form)
        self.lengthChangable.setObjectName("lengthChangable")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lengthChangable)
        self.diam = QtWidgets.QLabel(Form)
        self.diam.setObjectName("diam")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.diam)
        self.diamChangable = QtWidgets.QLineEdit(Form)
        self.diamChangable.setObjectName("diamChangable")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.diamChangable)
        self.matr = QtWidgets.QLabel(Form)
        self.matr.setObjectName("matr")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.matr)
        self.matCahngable = QtWidgets.QLineEdit(Form)
        self.matCahngable.setObjectName("matCahngable")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.matCahngable)
        self.horizontalLayout.addLayout(self.formLayout)
        self.edit_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_btn.sizePolicy().hasHeightForWidth())
        self.edit_btn.setSizePolicy(sizePolicy)
        self.edit_btn.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_btn.setStyleSheet("background-color: rgb(179, 179, 179);")
        self.edit_btn.setDefault(True)
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout.addWidget(self.edit_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.length.setText(_translate("Form", "Длина"))
        self.lengthChangable.setText(_translate("Form", "Длина"))
        self.diam.setText(_translate("Form", "Диаметр"))
        self.diamChangable.setText(_translate("Form", "Диаметр"))
        self.matr.setText(_translate("Form", "Материал"))
        self.matCahngable.setText(_translate("Form", "Материал"))
        self.edit_btn.setText(_translate("Form", " Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
